In [3]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

In [1]:
print('hi')

hi

In [4]:
from selenium import webdriver

driver=webdriver.Chrome()

driver.get("https://catalog.onliner.by/mobile")

In [5]:
# Собираем все ссылки на объявления с выбранной страницы
def get_all_links_on_page():
    elements = driver.find_elements(By.CLASS_NAME, value='catalog-form__link')
    # elements = driver.find_elements(by=By.CSS_SELECTOR, value="#container > div > div > div > div > div.catalog-content > div.catalog-wrapper > div > div > div.catalog-form__tabs > div > div > div > div > div.catalog-form__filter-part.catalog-form__filter-part_2 > div.catalog-form__offers > div > div:nth-child(1) > div > div > div.catalog-form__offers-part.catalog-form__offers-part_data > div.catalog-form__description.catalog-form__description_primary.catalog-form__description_base-additional.catalog-form__description_font-weight_semibold.catalog-form__description_condensed-other > a")
    # <a href="https://catalog.onliner.by/mobile/xiaomi/redmi15c8256ebk" class="catalog-form__link catalog-form__link_primary-additional catalog-form__link_base-additional catalog-form__link_font-weight_semibold catalog-form__link_nodecor"> Телефон Xiaomi Redmi 15C 4G 8GB/256GB международная версия (черный) </a>
    ads_list = []
    for element in elements:
        ads_list.append(element.get_attribute('href'))
        # print(element.get_attribute('href'), '\n')

    return ads_list

In [6]:
links = get_all_links_on_page()

In [7]:
links

['https://tech.onliner.by/2026/02/26/rating-smartphones',
 None,
 'https://catalog.onliner.by/mobile/samsung/sms731b8256bka8/prices',
 'https://catalog.onliner.by/mobile/samsung/sms731b8256bka8',
 'https://forum.onliner.by/viewtopic.php?t=26103928',
 'https://catalog.onliner.by/mobile/honor/x9d12256fg/prices',
 'https://catalog.onliner.by/mobile/honor/x9d12256fg',
 'https://forum.onliner.by/viewtopic.php?t=26116412',
 'https://catalog.onliner.by/mobile/honor/x8c8128wh/prices',
 'https://catalog.onliner.by/mobile/honor/x8c8128wh',
 'https://forum.onliner.by/posting.php?mode=newtopic&f=33&device=x8c8128wh',
 'https://catalog.onliner.by/mobile/honor/hx7e6256gllbl/prices',
 'https://catalog.onliner.by/mobile/honor/hx7e6256gllbl',
 'https://forum.onliner.by/viewtopic.php?t=26221387',
 'https://catalog.onliner.by/mobile/honor/x5dplus4128sl/prices',
 'https://catalog.onliner.by/mobile/honor/x5dplus4128sl',
 'https://forum.onliner.by/posting.php?mode=newtopic&f=33&device=x5dplus4128sl',
 'https://catalog.onliner.by/mobile/apple/ip18pro256bu/prices',
 'https://catalog.onliner.by/mobile/apple/ip18pro256bu/used',
 'https://catalog.onliner.by/mobile/apple/ip18pro256bu',
 'https://forum.onliner.by/viewtopic.php?t=26226769']

In [8]:
# Переход на следующую страницу через нажатие на кнопку
def click_next_page():
    clickable_element = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, '/html/body/div[2]/div/div/div/div/div/div/div/div/div[2]/div[1]/div/div/div[4]/div/div/div/div/div[3]/div[3]/a'))
    )

    clickable_element.click()

In [9]:
click_next_page()

TimeoutException: Message:
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	(No symbol) [0x7ff7073b01c5]
	(No symbol) [0x7ff7072c7990]
	(No symbol) [0x7ff7070d448d]
	(No symbol) [0x7ff70712faed]
	(No symbol) [0x7ff70712fdbc]
	(No symbol) [0x7ff707188937]
	(No symbol) [0x7ff7071855a4]
	(No symbol) [0x7ff707121892]
	(No symbol) [0x7ff7071226a3]
	(No symbol) [0x7ff7077bab51]
	(No symbol) [0x7ff7077e3aeb]
	(No symbol) [0x7ff7077d7fbe]
	(No symbol) [0x7ff7074b260e]
	(No symbol) [0x7ff7072d5085]
	(No symbol) [0x7ff7072d03f4]
	(No symbol) [0x7ff7072d0584]
	(No symbol) [0x7ff7072bab1c]
	(No symbol) [0x7ffdf1907344]
	(No symbol) [0x7ffdf2bdcc91]

In [10]:
len(links)

21

In [11]:
clear_links = []

for item in links:
    if item == None or 'forum.' in item or 'tech.' in item:
        pass
    else:
        clear_links.append(item)

len(clear_links)

13

In [12]:
very_clear_links = []

for item in clear_links:
    if 'prices' in item or 'reviews' in item or 'used' in item:
        pass
    else:
        very_clear_links.append(item)

len(very_clear_links)

6

In [13]:
def clean_links(links: list):
    print(f'Start size of links list: {len(links)}')
    clear_links = []
    very_clear_links = []

    for item in links:
        if item == None or 'forum.' in item or 'tech.' in item:
            pass
        else:
            clear_links.append(item)
    print(f'Current size of links list: {len(clear_links)}')

    for item in clear_links:
        if 'prices' in item or 'reviews' in item or 'used' in item:
            pass
        else:
            very_clear_links.append(item)
    print(f'Finish size of links list: {len(very_clear_links)}')

    return very_clear_links

In [14]:
very_clear_links

['https://catalog.onliner.by/mobile/samsung/sms731b8256bka8',
 'https://catalog.onliner.by/mobile/honor/x9d12256fg',
 'https://catalog.onliner.by/mobile/honor/x8c8128wh',
 'https://catalog.onliner.by/mobile/honor/hx7e6256gllbl',
 'https://catalog.onliner.by/mobile/honor/x5dplus4128sl',
 'https://catalog.onliner.by/mobile/apple/ip18pro256bu']

In [15]:
links_list = []
try:
    for iter in range(0, 5, 1):
        links_list += get_all_links_on_page()
        click_next_page()
except:
    print("All done")
    clean_links_list = clean_links(links_list)
finally:
    print("All done")
    clean_links_list = clean_links(links_list)

All done
Start size of links list: 21
Current size of links list: 13
Finish size of links list: 6
All done
Start size of links list: 21
Current size of links list: 13
Finish size of links list: 6

In [16]:
clean_links_list

['https://catalog.onliner.by/mobile/samsung/sms731b8256bka8',
 'https://catalog.onliner.by/mobile/honor/x9d12256fg',
 'https://catalog.onliner.by/mobile/honor/x8c8128wh',
 'https://catalog.onliner.by/mobile/honor/hx7e6256gllbl',
 'https://catalog.onliner.by/mobile/honor/x5dplus4128sl',
 'https://catalog.onliner.by/mobile/apple/ip18pro256bu']

In [17]:
with open('links.txt', 'a', encoding='utf-8') as file:
    for link in clean_links_list:
        file.write(link +'\n')

In [18]:
def get_characteristics():
    character_dict={}
    elements= driver.find_elements(By.CLASS_NAME, value='product-specs__table')
    for item in elements:
            tds=item.find_elements(By.TAG_NAME, value='td')
            for i in range(0, len(tds)-2):
                if tds[i].rect['width'] == 453:
                    character_dict.update({tds[i].text:tds[i+1].text})
    print(character_dict)


get_characteristics()

{}

In [19]:
def get_characteristics():
    character_dict=[]
    character_dict.append({'Название модели': driver.find_element(By.CLASS_NAME, value='catalog-masthead__title').text})
    elements= driver.find_elements(By.CSS_SELECTOR, value='.product-specs__table tr')
    for item in elements:
            tds = item.find_elements(By.TAG_NAME, value='td')
            if len(tds) == 2:
                if not tds[1].text:
                    if tds[1].find_elements(By.CLASS_NAME, value='i-x'):
                        character_dict.append({tds[0].text:'No'})
                    else:
                        character_dict.append({tds[0].text:'Yes'})
                else:
                    character_dict.append({tds[0].text:tds[1].text})


    return character_dict

In [20]:

clean_links_list = []
with open ('links.txt', 'r', encoding='utf_8') as l:
    while True:
        line = l.readline()
        clean_links_list.append(line)
        if not line:
            break
print(len(clean_links_list))

table=pd.DataFrame()
for link in clean_links_list[0:5]:
    driver.get(link)
    new_row=pd.DataFrame([get_characteristics()])
    table= pd.concat([table, new_row], ignore_index=True)
table

7

,0,1,2,3,4,5,6,7,8,9,...,94,95,96,97,98,99,100,101,102,103
0,{'Название модели': 'Телефон Samsung Galaxy S2...,{'Дата выхода на рынок': '2025 г.'},{'Операционная система': 'Android'},{'Версия ОС на момент выхода': 'Android 16'},{'Оболочка': 'One UI'},"{'Размер экрана': '6.7""'}",{'Разрешение экрана': '1080x2340'},{'Технология экрана': 'AMOLED (Dynamic AMOLED ...,{'Частота обновления экрана': '120 Гц'},{'Объем оперативной памяти': '8 ГБ'},...,{'Конструкция аккумулятора': 'несъемный'},{'Макс. время воспроизведения видео': '28 ч'},{'Мощность зарядки': '45 Вт'},"{'Комплект поставки': 'кабель USB-C - USB-C, с...",{'Чехол': 'No'},{'Перо (стилус)': 'No'},{'Акционное предложение': '+ наушники Samsung ...,{'Устройства в комплекте': 'Galaxy Buds Core (...,{'Модель': 'Samsung Galaxy S25 FE'},"{'Метки': '256 ГБ, водонепроницаемый, с ультра..."
1,{'Название модели': 'Телефон HONOR X9d 12GB/25...,{'Дата выхода на рынок': '2025 г.'},{'Операционная система': 'Android'},{'Версия ОС на момент выхода': 'Android 15'},{'Оболочка': 'Magic OS'},"{'Размер экрана': '6.79""'}",{'Разрешение экрана': '1200x2640'},{'Технология экрана': 'AMOLED'},{'Частота обновления экрана': '120 Гц'},{'Объем оперативной памяти': '12 ГБ'},...,{'Тип аккумулятора': 'Si-C'},{'Емкость аккумулятора': '8 300 мА·ч'},{'Конструкция аккумулятора': 'несъемный'},{'Мощность зарядки': '66 Вт'},"{'Комплект поставки': 'адаптер питания, кабель...",{'Чехол': 'Yes'},{'Перо (стилус)': 'No'},{'Модель': 'HONOR X9d'},"{'Метки': '256 ГБ, водонепроницаемый'}",NaN
2,{'Название модели': 'Телефон HONOR X8c ABR-LX1...,{'Дата выхода на рынок': '2025 г.'},{'Операционная система': 'Android'},{'Версия ОС на момент выхода': 'Android 15'},{'Оболочка': 'Magic OS'},"{'Размер экрана': '6.7""'}",{'Разрешение экрана': '1080x2412'},{'Технология экрана': 'AMOLED'},{'Частота обновления экрана': '120 Гц'},{'Объем оперативной памяти': '8 ГБ'},...,{'Чехол': 'Yes'},{'Перо (стилус)': 'No'},{'Модель': 'HONOR X8c'},"{'Метки': 'Onliner рекомендует, 128 ГБ, водоне...",NaN,NaN,NaN,NaN,NaN,NaN
3,{'Название модели': 'Телефон HONOR X7e LAB-LX1...,{'Дата выхода на рынок': '2026 г.'},{'Операционная система': 'Android'},{'Версия ОС на момент выхода': 'Android 16'},{'Оболочка': 'Magic OS'},"{'Размер экрана': '6.61""'}",{'Разрешение экрана': '720x1604'},{'Технология экрана': 'TFT'},{'Частота обновления экрана': '120 Гц'},{'Объем оперативной памяти': '6 ГБ'},...,{'Чехол': 'Yes'},{'Перо (стилус)': 'No'},{'Модель': 'HONOR X7e'},"{'Метки': 'бюджетный смартфон, 256 ГБ'}",NaN,NaN,NaN,NaN,NaN,NaN
4,{'Название модели': 'Телефон HONOR X5d Plus 4G...,{'Дата выхода на рынок': '2026 г.'},{'Операционная система': 'Android'},{'Версия ОС на момент выхода': 'Android 15'},{'Оболочка': 'Magic OS'},"{'Размер экрана': '6.74""'}",{'Разрешение экрана': '720x1600'},{'Технология экрана': 'TFT'},{'Частота обновления экрана': '90 Гц'},{'Объем оперативной памяти': '4 ГБ'},...,{'Мощность зарядки': '15 Вт'},"{'Комплект поставки': 'адаптер питания, кабель...",{'Чехол': 'Yes'},{'Перо (стилус)': 'No'},{'Модель': 'HONOR X5d Plus'},"{'Метки': 'бюджетный смартфон, 128 ГБ'}",NaN,NaN,NaN,NaN

In [21]:
table.shape[1]

104

In [22]:

lonest_str_index = 0
for i in range(0, table.shape[0]):
    if str(table[(table.shape[1]) -1 ][i]) != "nan":
        lonest_str_index = i

In [23]:

colmn_name=[]
for item in  table.loc[lonest_str_index]:
    for key, _ in item.items():
        colmn_name.append(key)

df= pd.DataFrame(columns=colmn_name)
df

Empty DataFrame
Columns: [Название модели, Дата выхода на рынок, Операционная система, Версия ОС на момент выхода, Оболочка, Размер экрана, Разрешение экрана, Технология экрана, Частота обновления экрана, Объем оперативной памяти, Объем встроенной памяти, Количество точек матрицы основной камеры, Характеристики блока камер, Максимальное разрешение видео, Беспроводная зарядка, Обратная беспроводная зарядка, Быстрая зарядка, Поддержка карт памяти, Количество физических SIM-карт, Формат SIM-карты, Раздельные слоты SIM 2 и карт памяти, Платформа, Процессор, Тактовая частота процессора, Количество ядер, Микроархитектура ЦПУ, Разрядность процессора, Техпроцесс, Графический ускоритель, Конструкция корпуса, Стереодинамики, Материал граней, Материал задней крышки, Цвет граней, Цвет задней крышки, Цвет фронтальной панели, Ударопрочный корпус, Пыле- и влагозащита, Физическая QWERTY-клавиатура, Сканер отпечатка пальца, Расположение сканера отпечатка пальца, Разблокировка по лицу, Функциональные особенности, Длина, Ширина, Толщина, Вес, Количество цветов экрана, Разрешающая способность экрана, Соотношение сторон, Яркость экрана (пиковая), Защита от царапин, Постоянная работа экрана, Динамический контроль частоты обновления (LTPO), Основной блок камер, Количество модулей камеры, Модули камер, Встроенная вспышка, Автоматическая фокусировка, Тип стабилизации, Оптический зум, Цифровой зум, Диафрагма основной камеры, Макс. количество кадров в секунду, Фронтальная камера, Характеристики фронтальной камеры, Расположение фронтальной камеры, Двойная камера, Автоматическая фокусировка, Встроенная вспышка, Диафрагма фронтальной камеры, Макс. разрешение видео фронтальной камеры, Акселерометр, Гироскоп, Датчик освещенности, Датчик приближения, Барометр, Монитор сердечного ритма, Измерение насыщенности крови кислородом, GPS, ГЛОНАСС, Beidou, GALILEO, Поддержка 4G (LTE), Поддержка 5G, Поддерживаемые частоты и полосы, Bluetooth, Аудиокодеки Bluetooth, Аудиовыход, Wi-Fi, Разъём подключения, NFC, Тип аккумулятора, Емкость аккумулятора, Конструкция аккумулятора, Макс. время воспроизведения видео, Мощность зарядки, Комплект поставки, Чехол, Перо (стилус), ...]
Index: []

[0 rows x 104 columns]